### PR TITLE
GF Update 2 : make fonts ready

### PR DESCRIPTION
**Pull request by RosaWagner**
- I tried to include all the original production features
- including the tables.fea and gdef.fea created more problems than it resolved so I generated fonts without.
- I would close my eyes on the remaining warnings, but tell me if you think it would be better to resolve them.
- Google requires now to have the same values for underline etc across the whole family, so I took the values of regular. Tell me if this is a problem.

- [x] now I have find out why the some font info don't export properly (usWeight class) when vertical metrics contained in the glyphs source are taken into account during generation.
- [x] have to check if use_typo_metrics parameter is taken into account because I have updated winAscent.
- [x] Add Rupee sign (I have no idea how to design a rupee, I took Ra and added a bar, thanks to correct if not good)

@MrBrezina : since I can't say if the devanagari has exported correctly, it is possible for you to check it before I send it to google ?

## Fontbakery report

Fontbakery version: 0.7.29

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Do we have the latest version of FontBakery installed?</summary>

* [com.google.fonts/check/fontbakery_version](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/fontbakery_version)

* 🔥 **FAIL** Unable to detect what's the latest version of FontBakery available. Maybe we're offline? Please check Internet access and try again.

</details>
<br>
</details>
<details>
<summary><b>[4] Eczar-Bold.ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Glyphs are similiar to Google Fonts version?</summary>

* [com.google.fonts/check/production_glyphs_similarity](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/production_glyphs_similarity)

* ⚠ **WARN** Following glyphs differ greatly from Google Fonts version: [dvKSPLa.MAR, uni0975, integral, dvKSPLa, uni0912, uni0914, uni0911, exclamdown, uni0913, uni0906]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---

Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will
only differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.

However, a quotedbl should have 2 contours, unless the font belongs to a
display family.

This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.

</pre>

* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: uni200C	Contours detected: 1	Expected: 0
Glyph name: uni200D	Contours detected: 1	Expected: 0
Glyph name: uni0904	Contours detected: 2	Expected: 1
Glyph name: uni0906	Contours detected: 2	Expected: 1
Glyph name: uni0913	Contours detected: 2	Expected: 1
Glyph name: uni0914	Contours detected: 2	Expected: 1
Glyph name: uni094A	Contours detected: 2	Expected: 1
Glyph name: uni0975	Contours detected: 2	Expected: 1
Glyph name: uni0908	Contours detected: 2	Expected: 1
Glyph name: uni090E	Contours detected: 2	Expected: 1
Glyph name: uni0910	Contours detected: 2	Expected: 1
Glyph name: uni0911	Contours detected: 3	Expected: 2
Glyph name: uni0912	Contours detected: 3	Expected: 1
Glyph name: uni0975	Contours detected: 2	Expected: 1
Glyph name: uni200C	Contours detected: 1	Expected: 0
Glyph name: uni090E	Contours detected: 2	Expected: 1
Glyph name: uni094A	Contours detected: 2	Expected: 1
Glyph name: uni0910	Contours detected: 2	Expected: 1
Glyph name: uni0912	Contours detected: 3	Expected: 1
Glyph name: uni0914	Contours detected: 2	Expected: 1
Glyph name: uni0911	Contours detected: 3	Expected: 2
Glyph name: uni0913	Contours detected: 2	Expected: 1
Glyph name: uni0908	Contours detected: 2	Expected: 1
Glyph name: uni0904	Contours detected: 2	Expected: 1
Glyph name: uni200D	Contours detected: 1	Expected: 0
Glyph name: uni0906	Contours detected: 2	Expected: 1 [code: contour-count]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).

</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + b
	- b + f
	- f + h
	- h + i
	- i + j
	- j + k
	- k + l
	- l + t

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class</summary>

* [com.google.fonts/check/gdef_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars)
<pre>--- Rationale ---

Mark characters should be in the GDEF mark glyph class.

</pre>

* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 U+0903, U+093B, U+093E, U+093F, U+0940, U+0949, U+094A, U+094B, U+094C and U+094F [code: mark-chars]

</details>
<br>
</details>
<details>
<summary><b>[4] Eczar-ExtraBold.ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Glyphs are similiar to Google Fonts version?</summary>

* [com.google.fonts/check/production_glyphs_similarity](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/production_glyphs_similarity)

* ⚠ **WARN** Following glyphs differ greatly from Google Fonts version: [dvKSPLa.MAR, uni0975, integral, dvKSPLa, uni0912, uni0914, uni0911, exclamdown, uni0913, uni0906]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---

Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will
only differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.

However, a quotedbl should have 2 contours, unless the font belongs to a
display family.

This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.

</pre>

* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: uni200C	Contours detected: 1	Expected: 0
Glyph name: uni200D	Contours detected: 1	Expected: 0
Glyph name: oslash	Contours detected: 2	Expected: 3
Glyph name: uni0904	Contours detected: 2	Expected: 1
Glyph name: uni0906	Contours detected: 2	Expected: 1
Glyph name: uni0913	Contours detected: 2	Expected: 1
Glyph name: uni0914	Contours detected: 2	Expected: 1
Glyph name: uni094A	Contours detected: 2	Expected: 1
Glyph name: uni0959	Contours detected: 5	Expected: 2 or 4
Glyph name: uni0975	Contours detected: 2	Expected: 1
Glyph name: Upsilonwithtonos	Contours detected: 3	Expected: 2
Glyph name: Upsilon	Contours detected: 2	Expected: 1
Glyph name: Upsilondieresis	Contours detected: 4	Expected: 3
Glyph name: uni0908	Contours detected: 2	Expected: 1
Glyph name: uni090E	Contours detected: 2	Expected: 1
Glyph name: uni0910	Contours detected: 2	Expected: 1
Glyph name: uni0911	Contours detected: 3	Expected: 2
Glyph name: uni0912	Contours detected: 3	Expected: 1
Glyph name: uni0916	Contours detected: 4	Expected: 1 or 3
Glyph name: Upsilonasper	Contours detected: 3	Expected: 2
Glyph name: Upsilonaspergrave	Contours detected: 4	Expected: 3
Glyph name: Upsilonasperacute	Contours detected: 4	Expected: 3
Glyph name: Upsilonaspertilde	Contours detected: 4	Expected: 3
Glyph name: Upsilonbreve	Contours detected: 3	Expected: 2
Glyph name: Upsilonwithmacron	Contours detected: 3	Expected: 2
Glyph name: Upsilongrave	Contours detected: 3	Expected: 2
Glyph name: Upsilonacute	Contours detected: 3	Expected: 2
Glyph name: uni0975	Contours detected: 2	Expected: 1
Glyph name: Upsilondieresis	Contours detected: 4	Expected: 3
Glyph name: uni0916	Contours detected: 4	Expected: 1 or 3
Glyph name: uni200C	Contours detected: 1	Expected: 0
Glyph name: uni090E	Contours detected: 2	Expected: 1
Glyph name: uni094A	Contours detected: 2	Expected: 1
Glyph name: uni0910	Contours detected: 2	Expected: 1
Glyph name: uni0912	Contours detected: 3	Expected: 1
Glyph name: Upsilon	Contours detected: 2	Expected: 1
Glyph name: uni0914	Contours detected: 2	Expected: 1
Glyph name: oslash	Contours detected: 2	Expected: 3
Glyph name: uni0911	Contours detected: 3	Expected: 2
Glyph name: uni0913	Contours detected: 2	Expected: 1
Glyph name: uni0908	Contours detected: 2	Expected: 1
Glyph name: uni0904	Contours detected: 2	Expected: 1
Glyph name: uni200D	Contours detected: 1	Expected: 0
Glyph name: uni0906	Contours detected: 2	Expected: 1
Glyph name: uni0959	Contours detected: 5	Expected: 2 or 4 [code: contour-count]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).

</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + b
	- b + f
	- f + h
	- h + i
	- i + j
	- j + k
	- k + l
	- l + t

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class</summary>

* [com.google.fonts/check/gdef_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars)
<pre>--- Rationale ---

Mark characters should be in the GDEF mark glyph class.

</pre>

* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 U+0903, U+093B, U+093E, U+093F, U+0940, U+0949, U+094A, U+094B, U+094C and U+094F [code: mark-chars]

</details>
<br>
</details>
<details>
<summary><b>[4] Eczar-Medium.ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Glyphs are similiar to Google Fonts version?</summary>

* [com.google.fonts/check/production_glyphs_similarity](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/production_glyphs_similarity)

* ⚠ **WARN** Following glyphs differ greatly from Google Fonts version: [dvKSPLa.MAR, integral, dvKSPLa, exclamdown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---

Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will
only differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.

However, a quotedbl should have 2 contours, unless the font belongs to a
display family.

This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.

</pre>

* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: uni200C	Contours detected: 1	Expected: 0
Glyph name: uni200D	Contours detected: 1	Expected: 0
Glyph name: asterisk	Contours detected: 5	Expected: 1 or 4
Glyph name: uni0904	Contours detected: 2	Expected: 1
Glyph name: uni0906	Contours detected: 2	Expected: 1
Glyph name: uni0913	Contours detected: 2	Expected: 1
Glyph name: uni0914	Contours detected: 2	Expected: 1
Glyph name: uni094A	Contours detected: 2	Expected: 1
Glyph name: uni0975	Contours detected: 2	Expected: 1
Glyph name: uni0908	Contours detected: 2	Expected: 1
Glyph name: uni090E	Contours detected: 2	Expected: 1
Glyph name: uni0910	Contours detected: 2	Expected: 1
Glyph name: uni0911	Contours detected: 3	Expected: 2
Glyph name: uni0912	Contours detected: 3	Expected: 1
Glyph name: uni0975	Contours detected: 2	Expected: 1
Glyph name: asterisk	Contours detected: 5	Expected: 1 or 4
Glyph name: uni200C	Contours detected: 1	Expected: 0
Glyph name: uni090E	Contours detected: 2	Expected: 1
Glyph name: uni094A	Contours detected: 2	Expected: 1
Glyph name: uni0910	Contours detected: 2	Expected: 1
Glyph name: uni0912	Contours detected: 3	Expected: 1
Glyph name: uni0914	Contours detected: 2	Expected: 1
Glyph name: uni0911	Contours detected: 3	Expected: 2
Glyph name: uni0913	Contours detected: 2	Expected: 1
Glyph name: uni0908	Contours detected: 2	Expected: 1
Glyph name: uni0904	Contours detected: 2	Expected: 1
Glyph name: uni200D	Contours detected: 1	Expected: 0
Glyph name: uni0906	Contours detected: 2	Expected: 1 [code: contour-count]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).

</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + b
	- b + f
	- f + h
	- h + i
	- i + j
	- j + k
	- k + l
	- l + t

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class</summary>

* [com.google.fonts/check/gdef_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars)
<pre>--- Rationale ---

Mark characters should be in the GDEF mark glyph class.

</pre>

* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 U+0903, U+093B, U+093E, U+093F, U+0940, U+0949, U+094A, U+094B, U+094C and U+094F [code: mark-chars]

</details>
<br>
</details>
<details>
<summary><b>[4] Eczar-Regular.ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Glyphs are similiar to Google Fonts version?</summary>

* [com.google.fonts/check/production_glyphs_similarity](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/production_glyphs_similarity)

* ⚠ **WARN** Following glyphs differ greatly from Google Fonts version: [dvKSPLa.MAR, integral, dvKSPLa, exclamdown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---

Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will
only differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.

However, a quotedbl should have 2 contours, unless the font belongs to a
display family.

This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.

</pre>

* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: uni200C	Contours detected: 1	Expected: 0
Glyph name: uni200D	Contours detected: 1	Expected: 0
Glyph name: asterisk	Contours detected: 5	Expected: 1 or 4
Glyph name: uni0904	Contours detected: 2	Expected: 1
Glyph name: uni0906	Contours detected: 2	Expected: 1
Glyph name: uni0913	Contours detected: 2	Expected: 1
Glyph name: uni0914	Contours detected: 2	Expected: 1
Glyph name: uni094A	Contours detected: 2	Expected: 1
Glyph name: uni0975	Contours detected: 2	Expected: 1
Glyph name: uni0908	Contours detected: 2	Expected: 1
Glyph name: uni090E	Contours detected: 2	Expected: 1
Glyph name: uni0910	Contours detected: 2	Expected: 1
Glyph name: uni0911	Contours detected: 3	Expected: 2
Glyph name: uni0912	Contours detected: 3	Expected: 1
Glyph name: uni0975	Contours detected: 2	Expected: 1
Glyph name: asterisk	Contours detected: 5	Expected: 1 or 4
Glyph name: uni200C	Contours detected: 1	Expected: 0
Glyph name: uni090E	Contours detected: 2	Expected: 1
Glyph name: uni094A	Contours detected: 2	Expected: 1
Glyph name: uni0910	Contours detected: 2	Expected: 1
Glyph name: uni0912	Contours detected: 3	Expected: 1
Glyph name: uni0914	Contours detected: 2	Expected: 1
Glyph name: uni0911	Contours detected: 3	Expected: 2
Glyph name: uni0913	Contours detected: 2	Expected: 1
Glyph name: uni0908	Contours detected: 2	Expected: 1
Glyph name: uni0904	Contours detected: 2	Expected: 1
Glyph name: uni200D	Contours detected: 1	Expected: 0
Glyph name: uni0906	Contours detected: 2	Expected: 1 [code: contour-count]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).

</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + b
	- b + f
	- f + h
	- h + i
	- i + j
	- j + k
	- k + l
	- l + t

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class</summary>

* [com.google.fonts/check/gdef_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars)
<pre>--- Rationale ---

Mark characters should be in the GDEF mark glyph class.

</pre>

* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 U+0903, U+093B, U+093E, U+093F, U+0940, U+0949, U+094A, U+094B, U+094C and U+094F [code: mark-chars]

</details>
<br>
</details>
<details>
<summary><b>[4] Eczar-SemiBold.ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Glyphs are similiar to Google Fonts version?</summary>

* [com.google.fonts/check/production_glyphs_similarity](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/production_glyphs_similarity)

* ⚠ **WARN** Following glyphs differ greatly from Google Fonts version: [dvKSPLa.MAR, integral, dvKSPLa, exclamdown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---

Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will
only differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.

However, a quotedbl should have 2 contours, unless the font belongs to a
display family.

This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.

</pre>

* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: uni200C	Contours detected: 1	Expected: 0
Glyph name: uni200D	Contours detected: 1	Expected: 0
Glyph name: asterisk	Contours detected: 5	Expected: 1 or 4
Glyph name: uni0904	Contours detected: 2	Expected: 1
Glyph name: uni0906	Contours detected: 2	Expected: 1
Glyph name: uni0913	Contours detected: 2	Expected: 1
Glyph name: uni0914	Contours detected: 2	Expected: 1
Glyph name: uni094A	Contours detected: 2	Expected: 1
Glyph name: uni0975	Contours detected: 2	Expected: 1
Glyph name: uni0908	Contours detected: 2	Expected: 1
Glyph name: uni090E	Contours detected: 2	Expected: 1
Glyph name: uni0910	Contours detected: 2	Expected: 1
Glyph name: uni0911	Contours detected: 3	Expected: 2
Glyph name: uni0912	Contours detected: 3	Expected: 1
Glyph name: uni0975	Contours detected: 2	Expected: 1
Glyph name: asterisk	Contours detected: 5	Expected: 1 or 4
Glyph name: uni200C	Contours detected: 1	Expected: 0
Glyph name: uni090E	Contours detected: 2	Expected: 1
Glyph name: uni094A	Contours detected: 2	Expected: 1
Glyph name: uni0910	Contours detected: 2	Expected: 1
Glyph name: uni0912	Contours detected: 3	Expected: 1
Glyph name: uni0914	Contours detected: 2	Expected: 1
Glyph name: uni0911	Contours detected: 3	Expected: 2
Glyph name: uni0913	Contours detected: 2	Expected: 1
Glyph name: uni0908	Contours detected: 2	Expected: 1
Glyph name: uni0904	Contours detected: 2	Expected: 1
Glyph name: uni200D	Contours detected: 1	Expected: 0
Glyph name: uni0906	Contours detected: 2	Expected: 1 [code: contour-count]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).

</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + b
	- b + f
	- f + h
	- h + i
	- i + j
	- j + k
	- k + l
	- l + t

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class</summary>

* [com.google.fonts/check/gdef_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars)
<pre>--- Rationale ---

Mark characters should be in the GDEF mark glyph class.

</pre>

* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 U+0903, U+093B, U+093E, U+093F, U+0940, U+0949, U+094A, U+094B, U+094C and U+094F [code: mark-chars]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 1 | 20 | 371 | 30 | 407 | 0 |
| 0% | 0% | 2% | 45% | 4% | 49% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

### CODE REVIEW

**Comment by MrBrezina** [comment]
@RosaWagner  Sorry it took ages to merge this! I missed that I need to do it. :)

**Comment by MrBrezina** [comment]
@RosaWagner let me know if there is anything you need from me.

**Comment by RosaWagner** [comment]
Haha thank you :) 
I would need you to review it, cause I am not sur if the devanagari looks good. 
We changed our workflow since July, I am gonna review the variable font on my side too.

**Comment by RosaWagner** [comment]
Yes so I think the indic script is broken.

**Pull request merged**
