### PR TITLE
Eczar ready for Google Fonts

### PR DESCRIPTION
**Pull request by yanone**
I was commissioned to prepare Eczar for publication on Google Fonts.
I removed all the old UFO and .fea files and moved everything into one variable Glyphs source (with the main .fea files remaining referenced in the Glpyhs source).
Please review and merge this PR before we can proceed with the publication. Thank you.

### CODE REVIEW

**Comment by yanone** [comment]
Update: I went the extra step and moved all feature code into the Glyph source. Now it generates both from Glyph as well as from fontmake. Previously, the `include()` statements would have worked only for either one.

**Comment by RosaWagner** [comment]
@MrBrezina @kontur Did you see this PR?

**Comment by kontur** [comment]
Wow, sorry, nope. Thanks @yanone for your work! I wasn't aware Eczar is actively being worked on and I've not previously worked on this typeface myself, nor did I have the repo on watch. Will confer with David and get back to this.

**Comment by MrBrezina** [comment]
That’s the thing. It is not actively worked on. We finished it years ago, it got released. This is a Google initiative to update it and merge it without any budget on our side, so I had very little time to keep up.

**Comment by RosaWagner** [comment]
@MrBrezina if merging this PR is a question of budget, you can reach out to Dave about that and see what he can do on his side. Otherwise, we can fork the repo into googlefonts and we move forward on our side, this way you don't have to spend time reviewing the PR, and we can make things happen quickly. What do you prefer?

**Comment by MrBrezina** [comment]
@RosaWagner in a long term, and in this particular case, I think you should make a fork. It doesn’t make sense that we would review your production work.

Note that I expect this to be different with Yrsa/Rasa or Handjet which we might be developing more actively in the future.

**Pull request merged**
